export default function handler(req, res) {
  const data = {
    lastUpdated: "6 April 2026",
    version: "2.1 — Telstra correction + spend minimisation",
    netPosition: -35394.64,
    totalAssets: 3290.09,
    totalDebt: 38684.73,
    monthlyIncome: 8442.08,
    monthlyOutgoings: 6800.25,
    monthlySurplus: 1641.83,
    optimisedSurplus: 2071.03,
    monthlyInterestCost: 316.24,
    debtFreeDate: {
      optimistic: "February 2028",
      currentTrajectory: "December 2028",
    },
    accounts: [
      { name: "Westpac Choice (814552) — Primary", type: "asset", balance: 1115.81, note: "Salary account" },
      { name: "Westpac Choice (576792) — Secondary", type: "asset", balance: 1089.04, note: "Personal loan DD" },
      { name: "Westpac Life (580656)", type: "asset", balance: 1085.24, note: "Savings buffer" },
      { name: "ANZ Low Rate CC (4019)", type: "debt", balance: -13670.00, rate: 0.00, note: "0% BT promo until Feb 2028. Set up DD — $20 late fee incurred.", priority: 4 },
      { name: "Westpac Personal Loan (095847)", type: "debt", balance: -10276.47, rate: 12, note: "Fixed rate, auto DD $795.80/mo. On track.", priority: 3 },
      { name: "Altitude Qantas Black CC (9294)", type: "debt", balance: -8572.54, rate: 20.00, note: "ATTACK FIRST. Stop using for daily spend.", priority: 1 },
      { name: "Low Rate Mastercard (3744)", type: "debt", balance: -6165.72, rate: 13.74, note: "Attack second. Jumped from $350 in Jan 2026.", priority: 2 },
    ],
    debtPayoffPlan: [
      { step: 1, name: "Altitude Qantas Black CC", balance: 8572.54, rate: 20.00, targetPayment: 2500, payoffDate: "Aug 2026", months: 4 },
      { step: 2, name: "Low Rate Mastercard", balance: 6165.72, rate: 13.74, targetPayment: 2500, payoffDate: "Nov 2026", months: 3 },
      { step: 3, name: "Westpac Personal Loan", balance: 10276.47, rate: 12, targetPayment: 795.80, payoffDate: "Jan 2027", months: 14 },
      { step: 4, name: "ANZ Low Rate CC (0% BT)", balance: 13670.00, rate: 0.00, targetPayment: 600, payoffDate: "Feb 2028", months: 23 },
    ],
    monthlyBreakdown: {
      income: [
        { label: "Buchan Group Salary", amount: 7647.08 },
        { label: "Rental Support (Clare Martin)", amount: 600.00 },
        { label: "Telstra Reimbursement (Buchan Group)", amount: 95.00, note: "$95 of $116.87 mobile bill covered by employer" },
        { label: "Medicare/Misc", amount: 100.00 },
      ],
      fixedOutgoings: [
        { label: "Rent (Sekisui House MAST)", amount: 2760.00 },
        { label: "Personal Loan repayment", amount: 750.00 },
        { label: "ANZ CC minimum payment", amount: 600.00 },
        { label: "Health Insurance (NIB)", amount: 155.82 },
        { label: "Car Insurance (Youi)", amount: 83.47 },
        { label: "Telstra Mobile (personal share)", amount: 21.87, note: "Full bill $116.87, $95 reimbursed by employer" },
        { label: "Telstra Broadband", amount: 80.00, note: "Review: switch to Aussie Broadband ~$65/mo" },
        { label: "Triclub (Jarrasport)", amount: 220.00 },
        { label: "Subscriptions (digital)", amount: 513.37, note: "Audit in progress — $69/mo cuttable immediately" },
        { label: "Loan Account Fee", amount: 15.00 },
        { label: "Bicycle Insurance", amount: 80.72 },
      ],
      variableOutgoings: [
        { label: "Groceries", amount: 650.00, target: 550.00 },
        { label: "Dining and Cafes", amount: 280.00, target: 180.00 },
        { label: "Sport Gear and Events", amount: 300.00, note: "March was $1,800+. No large spend until Aug 2026." },
        { label: "Pet (Petbarn)", amount: 60.00 },
        { label: "Transport", amount: 80.00 },
        { label: "Entertainment", amount: 150.00, target: 100.00 },
      ],
    },
    spendMinimisation: {
      immediateSubscriptionCuts: [
        { item: "Crunchyroll", saving: 11.99, action: "CANCEL" },
        { item: "Twitch", saving: 20.99, action: "CANCEL" },
        { item: "Uber One", saving: 9.99, action: "CANCEL" },
        { item: "Audible duplicate charge", saving: 17.91, action: "INVESTIGATE AND REMOVE" },
        { item: "Strava — switch to annual billing", saving: 8.32, action: "SWITCH" },
      ],
      businessClaimableSubscriptions: [
        { item: "Make.com", amount: 157.92, entity: "SWD/SARO", note: "Automation infrastructure" },
        { item: "Claude.ai (work component)", amount: 92.42, entity: "SARO/SWD", note: "~60% work use" },
        { item: "Anthropic API", amount: 32.17, entity: "SARO", note: "ARIA infrastructure" },
        { item: "Cloudflare", amount: 15.61, entity: "SWD/SARO", note: "Web infrastructure" },
        { item: "Squarespace", amount: 13.98, entity: "SARO", note: "SARO website" },
        { item: "Google Workspace", amount: 24.68, entity: "SARO", note: "Already claimed" },
      ],
      variableReductionTargets: [
        { category: "Groceries", current: 650, target: 550, saving: 100 },
        { category: "Dining and cafes", current: 280, target: 180, saving: 100 },
        { category: "Entertainment", current: 150, target: 100, saving: 50 },
        { category: "Broadband", current: 80, target: 65, saving: 15 },
      ],
      totalImmediateSaving: 69.20,
      totalVariableSaving: 265.00,
      optimisedSurplus: 2071.03,
    },
    recommendations: [
      {
        priority: "CRITICAL",
        title: "Stop using Altitude Qantas Black CC for daily spend",
        detail: "Every dollar spent on this card costs 20% p.a. in interest ($143/mo current drain). Transfer all daily spending to debit until this card is cleared Aug 2026.",
      },
      {
        priority: "CRITICAL",
        title: "Set up $2,500/mo auto-payment to Altitude Qantas Black CC",
        detail: "Current ad hoc payments are erratic. A fixed $2,500/mo direct debit clears the card by Aug 2026 and eliminates the $143/mo interest drain.",
      },
      {
        priority: "CRITICAL",
        title: "Set up ANZ BPAY direct debit (min $286/mo, target $600/mo)",
        detail: "A $20 late payment fee was charged 08/03/26. The 0% BT promo until Feb 2028 is too valuable to lose. Set up BPAY (biller code 6007) immediately.",
      },
      {
        priority: "HIGH",
        title: "Cancel Crunchyroll, Twitch, Uber One immediately",
        detail: "Combined saving: $42.97/mo. All three are non-essential discretionary services. Cancel today.",
      },
      {
        priority: "HIGH",
        title: "Fix Audible duplicate charge",
        detail: "Two Audible charges detected ($35.82/mo). Investigate and remove the duplicate. Saving: $17.91/mo.",
      },
      {
        priority: "HIGH",
        title: "Claim business subscriptions via SARO/SWD",
        detail: "Make.com, Claude.ai, Anthropic API, Cloudflare, Squarespace are legitimate business expenses totalling ~$320/mo. Tax deductible at 32.5% marginal rate.",
      },
      {
        priority: "HIGH",
        title: "No large discretionary spend until Altitude CC cleared (Aug 2026)",
        detail: "March 2026 sport spend was ~$1,800+ (QT Gold Coast $830, USM event $455, Giant bike $350). This delayed debt paydown. Freeze non-essential large purchases.",
      },
      {
        priority: "MEDIUM",
        title: "Reduce dining to $180/mo and groceries to $550/mo",
        detail: "Combined saving: $200/mo. Café frequency reduction and meal prep are the primary levers. Applies from May 2026.",
      },
      {
        priority: "MEDIUM",
        title: "Switch broadband provider to Aussie Broadband",
        detail: "Telstra Broadband costs $80/mo. Aussie Broadband equivalent plans run ~$65/mo. Saving: $15/mo. Mobile bill already has $95 employer reimbursement.",
      },
      {
        priority: "LOW",
        title: "Build $10k emergency fund in Westpac Life from Jan 2027",
        detail: "Once personal loan is paid off (Jan 2027), redirect $795/mo to Westpac Life savings. $10k buffer achievable by mid-2027.",
      },
    ],
    retirementProjection: {
      note: "Once debt-free (Feb 2028), free cashflow is approximately $3,411/mo",
      freeCashflowPostDebt: 3411,
      steps: [
        "Aug 2026: Altitude CC cleared. Redirect $2,500 to Low Rate MC.",
        "Nov 2026: Low Rate MC cleared. Begin salary sacrifice super (~$500-1,000/mo).",
        "Jan 2027: Personal loan cleared. Redirect $795/mo to emergency fund.",
        "Mid 2027: $10k emergency fund reached. Increase super salary sacrifice.",
        "Feb 2028: DEBT FREE. Full wealth building mode begins.",
        "Feb 2028+: ETF investment $1,000-1,500/mo (VGS/VAS split).",
        "Feb 2028+: Max concessional super ($19,075/yr salary sacrifice room). Tax saving ~$6,200/yr.",
        "Ongoing: SARO target $10k+/yr consulting. SWD target $500-1,000/mo passive income.",
      ],
    },
  };

  res.status(200).json(data);
}
